/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include"stm32_f103c6_GPIO.h"
#include "stm32f103x6.h"
#include "LCD.h"
#include "Keypad.h"

#define ZERO 0x01
#define ONE 0x79
#define TWO 0x24
#define THREE 0x30
#define FOUR 0x4C
#define FIVE 0x12
#define SIX 0x02
#define SEVEN 0x19
#define EIGHT 0x00
#define NINE 0x10

void delay(int x)
{
	uint32_t i,j;
	for(i=0;i<=x;i++)
		for(j=0;j<255;j++);
}

void Clock_INIT(void)
{
	//set on the clock for PORTA
	RCC_GPIOA_CLK_EN();
	//set on the clock for PORTB
	RCC_GPIOB_CLK_EN();
}

void GPIO_INIT(void)
{
	//init 7_segmant
	GPIO_Pinconfig_t pincfg;

	pincfg.pinNumber=GPIO_PIN_9;
	//PORTB Pin9 as output pull_push
	pincfg.GPIO_MODE=GPIO_MODE_OUTPUT_PP;
	pincfg.GPIO_OUTPUT_Speed=GPIO_speed_10M;
	MCAL_GPIO_Init(GPIOB,&pincfg);

	pincfg.pinNumber=GPIO_PIN_10;
	//PORTB Pin10 as output pull_push
	pincfg.GPIO_MODE=GPIO_MODE_OUTPUT_PP;
	pincfg.GPIO_OUTPUT_Speed=GPIO_speed_10M;
	MCAL_GPIO_Init(GPIOB,&pincfg);

	pincfg.pinNumber=GPIO_PIN_11;
	//PORTB Pin11 as output pull_push
	pincfg.GPIO_MODE=GPIO_MODE_OUTPUT_PP;
	pincfg.GPIO_OUTPUT_Speed=GPIO_speed_10M;
	MCAL_GPIO_Init(GPIOB,&pincfg);

	pincfg.pinNumber=GPIO_PIN_12;
	//PORTB Pin12 as output pull_push
	pincfg.GPIO_MODE=GPIO_MODE_OUTPUT_PP;
	pincfg.GPIO_OUTPUT_Speed=GPIO_speed_10M;
	MCAL_GPIO_Init(GPIOB,&pincfg);

	pincfg.pinNumber=GPIO_PIN_13;
	//PORTB Pin13 as output pull_push
	pincfg.GPIO_MODE=GPIO_MODE_OUTPUT_PP;
	pincfg.GPIO_OUTPUT_Speed=GPIO_speed_10M;
	MCAL_GPIO_Init(GPIOB,&pincfg);

	pincfg.pinNumber=GPIO_PIN_14;
	//PORTB Pin14 as output pull_push
	pincfg.GPIO_MODE=GPIO_MODE_OUTPUT_PP;
	pincfg.GPIO_OUTPUT_Speed=GPIO_speed_10M;
	MCAL_GPIO_Init(GPIOB,&pincfg);

	pincfg.pinNumber=GPIO_PIN_15;
	//PORTB Pin15 as output pull_push
	pincfg.GPIO_MODE=GPIO_MODE_OUTPUT_PP;
	pincfg.GPIO_OUTPUT_Speed=GPIO_speed_10M;
	MCAL_GPIO_Init(GPIOB,&pincfg);

}
int main(void)
{

	Clock_INIT();
	GPIO_INIT();
	LCD_init();
	LCD_String("HI");
	delay(30);
	lcd_Clear();
	char LCD_DISPLAY [11] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0'};
	char Seg_DISPLAY [11] = {ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, ZERO};

	for (char i = 0; i <= 10; i++)
	{
		LCD_Character(LCD_DISPLAY[i]);
		MCAL_GPIO_WritePort(GPIOB,Seg_DISPLAY[i]<< 9);
		delay(100);
	}
	lcd_Clear();
	LCD_String("Keypad is ready");
	delay(30);
	lcd_Clear();

	keypad_init();
	char key_pressed;
    while (1)
    {
		key_pressed=keypad_getkey();
		switch(key_pressed)
		{
			case 'c':
				lcd_Clear();
				break;
			case 'n':
				break;
			default:
				LCD_Character(key_pressed);
				break;
		}
    }

}

