/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include"stm32_f103c6_GPIO.h"
#include "stm32f103x6.h"



void delay(int x)
{
	uint32_t i,j;
	for(i=0;i<=x;i++)
		for(j=0;j<255;j++);
}

void Clock_INIT(void)
{
	//set on the clock for PORTA
	RCC_GPIOA_CLK_EN();
	//set on the clock for PORTB
	RCC_GPIOB_CLK_EN();
}

void GPIO_INIT(void)
{
	GPIO_Pinconfig_t pincfg;
	pincfg.pinNumber=GPIO_PIN_1;
	//PORTA Pin1 as Floating input
	pincfg.GPIO_MODE=GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA,&pincfg);

	//PORTB Pin1 as General purpose output push-pull
	pincfg.pinNumber=GPIO_PIN_1;
	pincfg.GPIO_MODE=GPIO_MODE_OUTPUT_PP;
	pincfg.GPIO_OUTPUT_Speed=GPIO_speed_10M;
	MCAL_GPIO_Init(GPIOB,&pincfg);

	//PORTA Pin13 as Floating input
	pincfg.pinNumber=GPIO_PIN_13;
	pincfg.GPIO_MODE=GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA,&pincfg);

	//PORTB Pin13 as General purpose output push-pull
	pincfg.pinNumber=GPIO_PIN_13;
	pincfg.GPIO_MODE=GPIO_MODE_OUTPUT_PP;
	pincfg.GPIO_OUTPUT_Speed=GPIO_speed_10M;
	MCAL_GPIO_Init(GPIOB,&pincfg);

}
int main(void)
{
	Clock_INIT();
	GPIO_INIT();

    while(1)
    {
    	if( MCAL_GPIO_ReadPin(GPIOA,GPIO_PIN_1) ==0)   //Single Pressing
    	{
    		MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
    		while(MCAL_GPIO_ReadPin(GPIOA,GPIO_PIN_1) ==0);
    	}

    	if(MCAL_GPIO_ReadPin(GPIOA,GPIO_PIN_13)==1)   //Multi Pressing
    	{
    		MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
    	}
    	delay(1);
    }
}

