/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "Platform_Types.h"
//clock
#define RCC_BASE        0x40021000
#define RCC_APB2ENR     *(volatile uint32_t *)(RCC_BASE+0x18)
//GPIO
#define GPIOA_BASE      0x40010800
#define GPIOB_BASE      0x40010C00
#define GPIOA_CRL       *(volatile uint32_t *)(GPIOA_BASE+0x00)
#define GPIOB_CRL       *(volatile uint32_t *)(GPIOB_BASE+0x00)
#define GPIOA_CRH       *(volatile uint32_t *)(GPIOA_BASE+0x04)
#define GPIOB_CRH       *(volatile uint32_t *)(GPIOB_BASE+0x04)
#define GPIOA_IDR       *(volatile uint32_t *)(GPIOA_BASE+0x08)
#define GPIOB_IDR       *(volatile uint32_t *)(GPIOB_BASE+0x08)
#define GPIOA_ODR       *(volatile uint32_t *)(GPIOA_BASE+0x0C)
#define GPIOB_ODR       *(volatile uint32_t *)(GPIOB_BASE+0x0C)


void delay(int x)
{
	uint32_t i,j;
	for(i=0;i<=x;i++)
		for(j=0;j<255;j++);
}

void Clock_INIT(void)
{
	//set on the clock for PORTA
	RCC_APB2ENR |=(1<<2);
	//set on the clock for PORTB
	RCC_APB2ENR |=(1<<3);
}

void GPIO_INIT(void)
{
	GPIOA_ODR =0X0;
	GPIOB_ODR =0X0;
	// Set GPIOA_CRL 0
	GPIOA_CRL=0X0;
	//PORTA Pin1 as Floating input
	GPIOA_CRL |=(1<<6);
	// Set GPIOB_CRL 0
	GPIOB_CRL=0X0;
	//PORTB Pin1 as General purpose output push-pull
	GPIOB_CRL |=(1<<4);
	// Set GPIOA_CRH 0
	GPIOA_CRH=0X0;
	//PORTA Pin13 as Floating input
	GPIOA_CRH |=(1<<22);
	// Set GPIOB_CRH 0
	GPIOB_CRH=0X0;
	//PORTB Pin13 as General purpose output push-pull
	GPIOB_CRH |=(1<<20);
}
int main(void)
{
	Clock_INIT();
	GPIO_INIT();

    while(1)
    {
    	if(((GPIOA_IDR & (1<<1))>>1)==0)   //Single Pressing
    	{
    		GPIOB_ODR ^=(1<<1);
    		while(((GPIOA_IDR & (1<<1))>>1)==0);
    	}

    	if(((GPIOA_IDR & (1<<13))>>13)==1)   //Multi Pressing
    	{
    		GPIOB_ODR ^=(1<<13);
    	}
    	delay(1);
    }
}
