/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include"stm32_f103c6_GPIO.h"
#include"stm32_f103c6_EXTI.h"
#include "stm32f103x6.h"
#include"stm32_f103c6_USART.h"
#include "LCD.h"
#include "Keypad.h"

unsigned char DATA  ;
unsigned char DATA2[100] ="s#";
uint16_t DATA1 = 300;
void Clock_INIT(void)
{
	//set on the clock for PORTA
	RCC_GPIOA_CLK_EN();
	//set on the clock for PORTB
	RCC_GPIOB_CLK_EN();
	//set on the clock for AFIO
	RCC_AFIO_CLK_EN();
}
 void USART1_IRQ_Call (void)
 {
	MCAL_USART_Receive_String(USART1, &DATA, Enable);
	MCAL_USART_Send_String(USART1, &DATA, Enable);
 }

int main(void)
{
	Clock_INIT();

	USART_config_t Config;
	Config.BAUDRATE=USART_BAUDRATE_115200 ;
	Config.HWFLOWCTL=USART_HWFLOWCTL_Disable;
	Config.IRQ_EN=USART_IRQ_ENABLE_RXNE;
	Config.MODE=USART_MODE_TX_RX;
	Config.NUM_DATA_BIT=USART_NUM_DATA_BIT_8;
	Config.NUM_STOP_BIT=USART_NUM_STOP_BIT_1;
	Config.PARITY=USART_PARITY_Disable;
	Config.P_IRQ_CALL=USART1_IRQ_Call;
	MCAL_USART_Init(USART1, &Config);
	MCAL_USART_Set_Pin(USART1);



	while (1)
	{

	}

}

